pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		maven {
			name = 'NeoForged'
			url = 'https://maven.neoforged.net/releases'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

// Multi-loader layout: common sources + fabric/neoforge loader modules
rootProject.name = 'spellgems'

include 'common'
include 'fabric'
include 'neoforge'
